### ISSUE TITLE
Logs() call is broken

### ISSUE THREAD

**Issue by jake-ciolek** [kraftcloud/go-sdk#6]
The instance example is broken and the Logs() call doesn't work anymore:

```sh
could not get instance logs: performing the request: error parsing response: json: Unmarshal(non-pointer kraftcloud.ServiceResponse[sdk.kraft.cloud/instance.Instance])
```

Ran into it while trying to adapt kraftkit to the refactored sdk.

**Comment by antoineco** [comment]
I wonder how the linter didn't catch that. Maybe it doesn't descend into submodules.

**Comment by antoineco** [comment]
I tried locally with absolutely all linters enabled, and none of them detected the issue 🥲
